[package]
name = "verify"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
verification-helper-math-divisors = { path = "../crates/math/divisors" }
verification-helper-util-io = { path = "../crates/util/io" }
