[package]
name = "library-rs-verify"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "verify"

[dependencies]
library-rs = { path = "../lib" }

[[bin]]
name = "aoj_itp1_3_d"
path = "src/bin/aoj_itp1_3_d.rs"
doc = false



