name: verify

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: Set up Rust (1.70.0)
        run: |
          rustup set profile minimal
          rustup install 1.70.0
          rustup override set nightly

      # required by cargo-udeps
      - name: Set up Rust (nightly)
        run: |
          rustup set profile minimal
          rustup install nightly
          rustup override set nightly

      - name: cargo test
        run: cargo test --all-targets

          
      - name: Run tests and create docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          RUSTDOCFLAGS: --html-in-header ./etc/docs_header.html --extend-css ./etc/docs.css --default-theme light
        run: |
          git branch -D gh-pages || true
          out=$(script -c "oj-verify run" -e /dev/null) || true
          git switch -c gh-pages
          echo "$out"
          mkdir -p ./verify
          echo "$out" > ./verify/log.txt
          sed -i -e "s/ghp_[a-zA-Z0-9]\{36\}/***/g" ./verify/log.txt
          cargo doc --no-deps
          mv ./target/doc/* .
          git add ./verify/log.txt
          git commit -m "update docs"
          git push -f origin gh-pages
